Description of constraints and variables..

$c_{i,j,k,l}$ - действие взятия кубика $j$-го цвета $i$-ым манипулятором из $k$-ой кучки $l$-ым номером. ($l$-номером - в смысле, кубик, который этот манипулятор взял первым - имеет первый номер и тд).

Тогда:

$c_{ijkl} \in \{0,1\}$

$c_{ijkl} \geq 0, c_{ijkl} \leq 1$

$\forall i,j,k, ~ l_2 \geq l_1 \Rightarrow c_{ijk,l_2} \geq c_{ijk,l_1}$ - не можем взять второй кубик в манипулятро, пока не взяли первый и тд.

$\forall j,k \sum_{i,l} c_{ijkl} \leq 1$ - берем каждый кубик опр.цвета $j$ из опр. кучки $k$ не более 1го раза

$\forall i,l \sum_{j,k} c_{ijkl} \leq 1$ - в каждом манипуляторе $i$ на опр. высоте $l$ не более 1го кубика

Введем $b_{ijl} = \sum_k c_{ijkl}$ - наличие кубика цвета $j$ в манипуляторе $i$ на высоте $l$ (уже не важно из какой кучки). Для этой переменной можно записать условия на бонус очков в каждом манипуляторе:

Если $a$, $b$, $c$ - бонусная последовательность цветов, то ее можно учесть след. образом для каждого манипулятора.
Пусть $d_i$ - действие выкладывания $i$ манипулятора. Тогда начисление бонусных баллов можно представить в виде переменной $\xi_i$:

$\xi_i \geq 0, \xi_i \leq 1$

У нас есть 6 возможных мест для последовательности из трех кубиков правильного цвета:
наличие на $j$ из 6 мест бонусной посл. в $i$ манипуляторе обозначим за $\pi_{ij}$. Тогда

$\pi_{ij} \geq 0$

$\pi_{i,0} \leq b_{i,0,a}$

$\pi_{i,0} \leq b_{i,0,a}$

$\pi_{i,0} \leq b_{i,1,b}$

$\pi_{i,0} \leq b_{i,2,c}$

и так далее для $\pi_{i,1..}$


Двух бонусных последовательностей в одном манипуляторе быть не может, поэтому
$\xi_i \leq \sum_j \pi_{i,j}$ and $\forall\; i\; \xi_i \in \{0, 1\}$

Соответственно, если есть бонусная посл., то $\xi_i \in \{0,1\}$, а если ее нет, то $\xi_i = 0$. Поэтому, если добавить слагаемое $+A \xi_i$, то $\max...$ будет выбирать его $1$ при возможности.


А для учитывания уже конкретно наличия бонуса в 30 очков остается проверить, выложили ли мы эту башенку:

$\zeta_i \leq \xi_i, \zeta_i \leq d_i, \zeta_i \geq 0$

**obj $ .. + 30\sum_i \zeta_i$ **

Чтобы учесть взятие кубиков с разных сторон, на самом деле, у нас будут переменные $p_{ijklm}$. Здесь $m$ отвечает за то, с какой из 4х сторон мы подъехали к кубику $i$ манипулятором. Не всегда все из этих подъездов возможны. Пусть кубик цвета $j_2$  блокируют подъезд к кубику $j_1$ со стороны $m = 0$. Тогда, 
$index(p_{i,j_1,klm}) \geq \sum_{i,m,l} index(p_{i,j_2,klm})$
Для других цветов пар $j_1$,$j_2$ и подъездов $m$ необходимо написать такие же условия, если блокирует.


Основная переменная - матрица $x_{ij}$.  $x_{ij} = 1$, если j-е действие ($a_j$) является i-ым в порядке выполнения.

$index(a_j) = (1,2,3...)^\top x_{ij}$ 
-дает порядковый номер действия $a_j$, если оно включено в выбранную последовательность. Иначе 0.

Время. Пусть мы тратим на действия $\omega_i$ времени, а на переезды между действиями $\Omega_{ij}$.


$T_1 = \sum_{ij} \sum_N x_{N,i} x_{N-1,j} \Omega_{ij} $,

$T_2 = \omega_j \sum_i x_{ij}$


$T = T_1 + T_2$

objective - формируется за собранные кубики. За каждый кубик дается равно его высоте количество очков, начинается с 1. (+бонус). Запишем в $t_i$ очки за каждую башню:

$t_i = \sum_{j,i} b_{i,j,l}$ ... Но пока $t_i = 5$. И набираемые очки за это фиксированы, максимизировать их не нужно.

$\max_i \sum_i \zeta_i$

бонус +

брать кубики с разных сторон +

выкладываться + 

выкладываться в разных точках ?

разная высота башен -


# Create matrix of moving times

In [1]:
import numpy as np

In [44]:
v = 20
t_p = 2 # time of picking
t_r = 1 # time of rotation on pi / 2
t_m = 2 # time of moving on 6 cm

In [12]:
picking_points = np.zeros((5, 4, 3, 3))
cubes_coords = np.array([[0, -1], [1, 0], [0, 1], [-1, 0], [0, 0]])
l1 = np.array([[[1, 0], [0, 1], [-1, 0]],
               [[0, 1], [-1, 0], [0, -1]],
               [[-1, 0], [0, -1], [1, 0]],
               [[0, -1], [1, 0], [0, 1]]])

picking_points[..., :2] = cubes_coords[:, np.newaxis, np.newaxis, :] + l1[np.newaxis, :, :, :]
picking_points[..., 2] = np.array(range(4))[np.newaxis, :, np.newaxis]

In [13]:
picking_points

array([[[[ 1., -1.,  0.],
         [ 0.,  0.,  0.],
         [-1., -1.,  0.]],

        [[ 0.,  0.,  1.],
         [-1., -1.,  1.],
         [ 0., -2.,  1.]],

        [[-1., -1.,  2.],
         [ 0., -2.,  2.],
         [ 1., -1.,  2.]],

        [[ 0., -2.,  3.],
         [ 1., -1.,  3.],
         [ 0.,  0.,  3.]]],


       [[[ 2.,  0.,  0.],
         [ 1.,  1.,  0.],
         [ 0.,  0.,  0.]],

        [[ 1.,  1.,  1.],
         [ 0.,  0.,  1.],
         [ 1., -1.,  1.]],

        [[ 0.,  0.,  2.],
         [ 1., -1.,  2.],
         [ 2.,  0.,  2.]],

        [[ 1., -1.,  3.],
         [ 2.,  0.,  3.],
         [ 1.,  1.,  3.]]],


       [[[ 1.,  1.,  0.],
         [ 0.,  2.,  0.],
         [-1.,  1.,  0.]],

        [[ 0.,  2.,  1.],
         [-1.,  1.,  1.],
         [ 0.,  0.,  1.]],

        [[-1.,  1.,  2.],
         [ 0.,  0.,  2.],
         [ 1.,  1.,  2.]],

        [[ 0.,  0.,  3.],
         [ 1.,  1.,  3.],
         [ 0.,  2.,  3.]]],


       [[[ 0.,  0.,  0.],
        

In [25]:
points_2 = np.reshape(picking_points, (60, 3))
small_time_2 = t_m * np.abs(points_2[:, np.newaxis, 0] - points_2[np.newaxis, :, 0]) + \
             t_m * np.abs(points_2[:, np.newaxis, 1] - points_2[np.newaxis, :, 1]) + \
             t_r * ((points_2[:, np.newaxis, 2] - points_2[np.newaxis, :, 1]) % 4)

In [26]:
small_time = np.where(small_time_2 == 0, 0, small_time_2 + t_p)
small_time

array([[  3.,   6.,   7., ...,   5.,   4.,  11.],
       [  7.,   0.,   7., ...,   5.,   4.,   7.],
       [  7.,   6.,   3., ...,   5.,   8.,  11.],
       ..., 
       [  4.,   7.,   4., ...,   0.,   9.,   8.],
       [  4.,   7.,   8., ...,   6.,   5.,   8.],
       [  8.,   7.,   8., ...,   6.,   9.,   4.]])

In [27]:
small_time_2

array([[ 1.,  4.,  5., ...,  3.,  2.,  9.],
       [ 5.,  0.,  5., ...,  3.,  2.,  5.],
       [ 5.,  4.,  1., ...,  3.,  6.,  9.],
       ..., 
       [ 2.,  5.,  2., ...,  0.,  7.,  6.],
       [ 2.,  5.,  6., ...,  4.,  3.,  6.],
       [ 6.,  5.,  6., ...,  4.,  7.,  2.]])

In [45]:
heap_points = np.array([[54, 85, 0], [119, 30, 0], [150, 110, 0], [150, 190, 0], [119, 270, 0], [54, 215, 0]])
all_picking_points = np.reshape(points_2[np.newaxis, :, :2] * 6 + heap_points[:, np.newaxis, :2], (360, 2))
times = np.sum((all_picking_points[:, np.newaxis] - all_picking_points[np.newaxis, :]) ** 2, axis=2) ** 0.5 / v + t_p
for i in range(6):
    times[i * 60: (i + 1) * 60, i * 60: (i + 1) * 60] = small_time

In [46]:
times

array([[ 3.        ,  6.        ,  7.        , ...,  8.50691939,
         8.8       ,  9.1063352 ],
       [ 7.        ,  0.        ,  7.        , ...,  8.2       ,
         8.50691939,  8.8       ],
       [ 7.        ,  6.        ,  3.        , ...,  8.50691939,
         8.82641927,  9.1063352 ],
       ..., 
       [ 8.50691939,  8.2       ,  8.50691939, ...,  0.        ,
         9.        ,  8.        ],
       [ 8.8       ,  8.50691939,  8.82641927, ...,  6.        ,
         5.        ,  8.        ],
       [ 9.1063352 ,  8.8       ,  9.1063352 , ...,  6.        ,
         9.        ,  4.        ]])